# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: dbloja
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d
  web:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: builder
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"